update

diff --git a/confd/bigdata-client/templates/start-kylin.sh.tmpl b/confd/bigdata-client/templates/start-kylin.sh.tmpl
--- a/confd/bigdata-client/templates/start-kylin.sh.tmpl
+++ b/confd/bigdata-client/templates/start-kylin.sh.tmpl
@@ -1,53 +1,79 @@
 #!/bin/bash
 source /etc/profile
+source /home/kylin/.profile  
+source /opt/kap-plus/sbin/kylinutil.sh
 
-#check1:check hive is ready or not 
-/opt/hive/bin/hive -e "show databases;"    
-if [  $? -ne 0 ] 
-then 
-	echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - Warning - HIVE is not running,could not start Kylin." 1>>$KYLINAPP_LOG  2>&1
-	exit 0 
-else
-	echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - INFO - HIVE is running,could start Kylin." 1>>$KYLINAPP_LOG  2>&1
-fi 
+######################################################################################################################################## 
+enable_kylin={{getv "/env/enable_kylin"}}
+enable_hive={{getv "/env/enable_hive"}}  
  
-#check2:check zookeeper env param is setted or not.  
-zkport=""
+zkport="" 
 {{range $service_name := lsdir "/links" | filter "zookeeper4kylin*"}}
 {{$port := getv (printf "/links/%s/cluster/endpoints/client/port" $service_name)}}  
 zkport={{$port}}
-{{end}} 
+{{end}}  
 
-if [ "$zkport"x == ""x ]
+#检查参数配置是否正确,正确启动服务，不正确给出错误信息到日志。  
+#0.参数设置正确，启动KAP和KyAnalyzer服务
+if [ "$enable_hive"x == "true"x ] && [ "$enable_hive"x == "true"x ] && [ "$zkport"x != ""x ]
 then
-	echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - Error - zookeeper4kylin does not exit,could not start Kylin." 1>>$KYLINAPP_LOG  2>&1
-	exit 1	
-fi 
-  
-source /home/kylin/.profile    
-USER=kylin /opt/kap-plus/bin/kylin.sh start  1>>$KYLINAPP_LOG  2>&1
+	#启动前检查Hive 是否running，检查等待时间是500s	  
+	isHiveRunning=$(checkHiveIsRunning)
+	 
+	if [ "$isHiveRunning"x == "true"x ]
+	then
+		$(StartKAP)
+		if [  $? -ne 0 ] 
+		then 
+			echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - Error - Start Kylin Service failed." 1>>$KYLINAPP_LOG  2>&1	 
+			exit 1  
+		fi
+		
+		$(StartKyAnalyzer) 
+		if [  $? -ne 0 ] 
+		then 
+			echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - Error - Start kyanalyzer Service failed." 1>>$KYLINAPP_LOG  2>&1	 
+			exit 1  
+		fi
+		
+		echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - INFO - Start KAP and kyanalyzer Service successfully." 1>>$KYLINAPP_LOG  2>&1 
+		exit 0 
+	else
+		echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - Error - Wait hive to start for 500s,but hive is still not running,kylin can not start." 1>>$KYLINAPP_LOG  2>&1 
+		exit 1
+	fi 
+	 
+fi
 
-pid=`ps ax | grep kylin | grep -v grep | grep -v 'su kylin' | grep -v 'bash' | grep 'Dkylin.hive.dependency' | awk '{print $1}'` 
-if [ "$pid"x == ""x ]
-then 
-	 echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - Error - Start Kylin Service failed." 1>>$KYLINAPP_LOG  2>&1	 
-     exit 1
-fi 
-echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - INFO - Started Kylin Service successfully." 1>>$KYLINAPP_LOG  2>&1
- 
- 
- 
-USER=kylin /opt/kyanalyzer/start-analyzer.sh  1>>$KYLINAPP_LOG  2>&1 
-pid=`ps ax | grep kyanalyzer | grep -v grep  | awk '{print $1}'`
-if [ "$pid"x == ""x ]
-then 
-	 echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - Error - Start kyanalyzer Service failed." 1>>$KYLINAPP_LOG  2>&1	 
-     exit 1
+#1.设置enable_kylin为false，检查是否有启动的kylin服务，如果有就关闭，如果没有直接退出。   
+if [ "$enable_kylin"x == "false"x ]
+then
+	echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - INFO - enable_kylin is disabled,No need to start Kylin. " 1>>$KYLINAPP_LOG  2>&1 
+	/opt/kap-plus/sbin/stop-kylin.sh  
+	exit 0	
 fi  
-echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - INFO - Started KyAnalyzer Service successfully." 1>>$KYLINAPP_LOG  2>&1 
-  
 
-exit 0
+
+#2.设置enable_kylin为true,enable_hive 为false，参数错误，启动失败  
+if [ "$enable_kylin"x == "true"x ] && [ "$enable_hive"x == "false"x ]
+then
+	echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - Error - Wrong user parameters:hive is disabled,can not start Kylin!" 1>>$KYLINAPP_LOG  2>&1 
+	exit 1 
+fi  
+
+#3.设置enable_kylin为true,设置enable_hive为true,zkport 为未设置，参数错误，启动失败。
+if [ "$enable_kylin"x == "true"x ] && [ "$enable_hive"x == "true"x ] && [ "$zkport"x == ""x ]
+then
+	echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - Error - Wrong user parameters:no zk service,can not start Kylin!" 1>>$KYLINAPP_LOG  2>&1 
+	exit 1
+fi 
+ 	 
+
+#4.其他未考虑到的参数设置都为错误设置，直接报错退出。
+echo "`date '+%Y-%m-%d %H:%M:%S'` - start-kylin.sh - Error - Wrong user parameters:other wrong settings,can not start Kylin!" 1>>$KYLINAPP_LOG  2>&1 
+exit 1
+ 
+  
 
 
  
